collections:
    features:
    authors:
    examples:
    details:

defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
    - scope:
          path: ""
      values:
          layout: "default"
jekyll-minifier:
    remove_spaces_inside_tags: true # Default: true
    remove_multi_spaces: true # Default: true
    remove_comments: true # Default: true
    remove_intertag_spaces: true # Default: false
    remove_quotes: false # Default: false
    compress_css: true # Default: true
    compress_javascript: true # Default: true
    compress_json: true # Default: true
    simple_doctype: false # Default: false
    remove_script_attributes: false # Default: false
    remove_style_attributes: false # Default: false
    remove_link_attributes: false # Default: false
    remove_form_attributes: false # Default: false
    remove_input_attributes: false # Default: false
    remove_javascript_protocol: false # Default: false
    remove_http_protocol: false # Default: false
    remove_https_protocol: false # Default: false
    preserve_line_breaks: false # Default: false
    simple_boolean_attributes: false # Default: false
    compress_js_templates: false # Default: false
    preserve_patterns: # Default: (empty)
    uglifier_args: # Default: (empty)
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-minifier
